version: 2
shared: &shared
    docker:
      - image: synocommunity/spksrc:latest
    working_directory: /spksrc
    steps:
      - checkout
      - run PKG=${CIRCLE_TAG%-*}
      - run: make setup
      - run: cd spk/$PKG && make $SYNOARCH"
      - run: ls packages/*.spk

jobs:
  "x64-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-x64-6.1
  "arch-x64-5.2":
    <<: *shared
    environment:
      - SYNOARCH=arch-arch-x64-5.2
  "x64-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-x64-6.1
  "88f6281-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-88f6281-6.1
  "alpine-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-alpine-6.1
  "armada370-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armada370-6.1
  "armada375-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armada375-6.1
  "armada38x-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armada38x-6.1
  "armadaxp-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armadaxp-6.1
  "comcerto2k-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-comcerto2k-6.1
  "denverton-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-denverton-6.1
  "evansport-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-evansport-6.1
  "hi3535-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-hi3535-6.1
  "ipq806x-1.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-ipq806x-1.1
  "monaco-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-monaco-6.1
  "northstarplus-1.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-northstarplus-1.1
  "qoriq-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-qoriq-6.1
  "rtd1296-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-rtd1296-6.1
  "ppc853x-5.2":
    <<: *shared
    environment:
      - SYNOARCH=arch-ppc853x-5.2


workflows:
  version: 2
  tagged-build:
    jobs:
      - "build-x64-6.1":
          filters:
            branches:
              ignore: /.*/
      - "x64-6.1":
          filters:
            branches:
              ignore: /.*/
      - "arch-x64-5.2":
          filters:
            branches:
              ignore: /.*/
      - "x64-6.1":
          filters:
            branches:
              ignore: /.*/
      - "88f6281-6.1":
          filters:
            branches:
              ignore: /.*/
      - "alpine-6.1":
          filters:
            branches:
              ignore: /.*/
      - "armada370-6.1":
          filters:
            branches:
              ignore: /.*/
      - "armada375-6.1":
          filters:
            branches:
              ignore: /.*/
      - "armada38x-6.1":
          filters:
            branches:
              ignore: /.*/
      - "armadaxp-6.1":
          filters:
            branches:
              ignore: /.*/
      - "comcerto2k-6.1":
          filters:
            branches:
              ignore: /.*/
      - "denverton-6.1":
          filters:
            branches:
              ignore: /.*/
      - "evansport-6.1":
          filters:
            branches:
              ignore: /.*/
      - "hi3535-6.1":
          filters:
            branches:
              ignore: /.*/
      - "ipq806x-1.1":
          filters:
            branches:
              ignore: /.*/
      - "monaco-6.1":
          filters:
            branches:
              ignore: /.*/
      - "northstarplus-1.1":
          filters:
            branches:
              ignore: /.*/
      - "qoriq-6.1":
          filters:
            branches:
              ignore: /.*/
      - "rtd1296-6.1":
          filters:
            branches:
              ignore: /.*/
      - "ppc853x-5.2":
          filters:
            branches:
              ignore: /.*/
