---
version: 2
shared: &shared
  docker:
    - image: synocommunity/spksrc:latest
  working_directory: /spksrc
  steps:
    - checkout
    - run: PKG=${CIRCLE_TAG%-*}
    - run: make setup
    - run: cd spk/$PKG && make "$SYNOARCH"
    - run: ls packages/*.spk
tags_only_filter: &filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/
jobs:
  "x64-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-x64-6.1
  "x64-5.2":
    <<: *shared
    environment:
      - SYNOARCH=arch-arch-x64-5.2
  "88f6281-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-88f6281-6.1
  "alpine-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-alpine-6.1
  "armada370-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armada370-6.1
  "armada375-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armada375-6.1
  "armada38x-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armada38x-6.1
  "armadaxp-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-armadaxp-6.1
  "comcerto2k-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-comcerto2k-6.1
  "denverton-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-denverton-6.1
  "evansport-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-evansport-6.1
  "hi3535-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-hi3535-6.1
  "ipq806x-1.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-ipq806x-1.1
  "monaco-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-monaco-6.1
  "northstarplus-1.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-northstarplus-1.1
  "qoriq-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-qoriq-6.1
  "rtd1296-6.1":
    <<: *shared
    environment:
      - SYNOARCH=arch-rtd1296-6.1
  "ppc853x-5.2":
    <<: *shared
    environment:
      - SYNOARCH=arch-ppc853x-5.2
workflows:
  version: 2
  tagged-build:
    jobs:
      - "x64-6.1":
          <<: *tags_only_filter
      - "x64-5.2":
          <<: *tags_only_filter
      - "88f6281-6.1":
          <<: *tags_only_filter
      - "alpine-6.1":
          <<: *tags_only_filter
      - "armada370-6.1":
          <<: *tags_only_filter
      - "armada375-6.1":
          <<: *tags_only_filter
      - "armada38x-6.1":
          <<: *tags_only_filter
      - "armadaxp-6.1":
          <<: *tags_only_filter
      - "comcerto2k-6.1":
          <<: *tags_only_filter
      - "denverton-6.1":
          <<: *tags_only_filter
      - "evansport-6.1":
          <<: *tags_only_filter
      - "hi3535-6.1":
          <<: *tags_only_filter
      - "ipq806x-1.1":
          <<: *tags_only_filter
      - "monaco-6.1":
          <<: *tags_only_filter
      - "northstarplus-1.1":
          <<: *tags_only_filter
      - "qoriq-6.1":
          <<: *tags_only_filter
      - "rtd1296-6.1":
          <<: *tags_only_filter
      - "ppc853x-5.2":
          <<: *tags_only_filter
